//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NationalInstruments.Analyzers.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NationalInstruments.Analyzers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All restricted types should be defined under &apos;NationalInstruments.Restricted&apos;..
        /// </summary>
        internal static string LRN001_Description {
            get {
                return ResourceManager.GetString("LRN001_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The namespace &apos;{0}&apos; should be renamed to &apos;NationalInstruments.Restricted&apos;.
        /// </summary>
        internal static string LRN001_Message {
            get {
                return ResourceManager.GetString("LRN001_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There is only one restricted namespace.
        /// </summary>
        internal static string LRN001_Title {
            get {
                return ResourceManager.GetString("LRN001_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All types should be in the &apos;NationalInstruments&apos; namespace..
        /// </summary>
        internal static string LRT001_Description {
            get {
                return ResourceManager.GetString("LRT001_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not in the &apos;NationalInstruments&apos; namespace.
        /// </summary>
        internal static string LRT001_Message {
            get {
                return ResourceManager.GetString("LRT001_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All types are in &apos;NationalInstruments&apos; namespace.
        /// </summary>
        internal static string LRT001_Title {
            get {
                return ResourceManager.GetString("LRT001_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To enable fully backwards-compatible database migrations in EntityFramework, all columns in the DB should be nullable. This means DbSet cannot use value types (unless they are marked as [NotMapped]) or types that implement IEnumerable&lt;T&gt; (we don&apos;t know how they&apos;ll be handled)..
        /// </summary>
        internal static string NI0017_Description {
            get {
                return ResourceManager.GetString("NI0017_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DbSet uses an IEnumerable that we don&apos;t know how EntityFramework will handle: {0} for {1} in {2}.
        /// </summary>
        internal static string NI0017_Diagnostic_IEnumerable {
            get {
                return ResourceManager.GetString("NI0017_Diagnostic_IEnumerable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DbSet creates non-nullable columns: {0} for {1} in {2} is a value type.
        /// </summary>
        internal static string NI0017_Diagnostic_ValueType {
            get {
                return ResourceManager.GetString("NI0017_Diagnostic_ValueType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Database columns should be nullable.
        /// </summary>
        internal static string NI0017_Title {
            get {
                return ResourceManager.GetString("NI0017_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Private field &apos;{0}&apos; must begin with an underscore and be camel-cased.
        /// </summary>
        internal static string NI1001_Message {
            get {
                return ResourceManager.GetString("NI1001_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Private, mutable fields must begin with underscore and be camel-cased.
        /// </summary>
        internal static string NI1001_Title {
            get {
                return ResourceManager.GetString("NI1001_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; with Scope &apos;{1}&apos; in file &apos;{2}&apos; is missing a Target value..
        /// </summary>
        internal static string NI1004_AttributeMissingTarget_Message {
            get {
                return ResourceManager.GetString("NI1004_AttributeMissingTarget_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rather than using string literals, use a string resource (.resx), unless this string will never be displayed to users..
        /// </summary>
        internal static string NI1004_Description {
            get {
                return ResourceManager.GetString("NI1004_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use a string resource in a .resx file instead of string literal &apos;{0}&apos;.
        /// </summary>
        internal static string NI1004_Message {
            get {
                return ResourceManager.GetString("NI1004_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do not use string literals in code.
        /// </summary>
        internal static string NI1004_Title {
            get {
                return ResourceManager.GetString("NI1004_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IWeakEventListener.ReceiveWeakEvents() must return true..
        /// </summary>
        internal static string NI1005_Description {
            get {
                return ResourceManager.GetString("NI1005_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IWeakEventListener.ReceiveWeakEvents() must return true.
        /// </summary>
        internal static string NI1005_Message {
            get {
                return ResourceManager.GetString("NI1005_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do not return false from IWeakEventListener.ReceiveWeakEvents().
        /// </summary>
        internal static string NI1005_Title {
            get {
                return ResourceManager.GetString("NI1005_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alternative: {0}.
        /// </summary>
        internal static string NI1006_AdditionalInfo_Alternative {
            get {
                return ResourceManager.GetString("NI1006_AdditionalInfo_Alternative", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Banned in this assembly..
        /// </summary>
        internal static string NI1006_AdditionalInfo_BannedInThisAssembly {
            get {
                return ResourceManager.GetString("NI1006_AdditionalInfo_BannedInThisAssembly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Justification: {0}.
        /// </summary>
        internal static string NI1006_AdditionalInfo_Justification {
            get {
                return ResourceManager.GetString("NI1006_AdditionalInfo_Justification", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to These methods have been banned from NG code. Contact an architect for explanation..
        /// </summary>
        internal static string NI1006_Description {
            get {
                return ResourceManager.GetString("NI1006_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replace &apos;{0}&apos; with a non-banned method or get permission to suppress this rule.{1}  See http://nitalk.natinst.com/docs/DOC-153475 for more information.
        /// </summary>
        internal static string NI1006_Message {
            get {
                return ResourceManager.GetString("NI1006_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do not use banned methods.
        /// </summary>
        internal static string NI1006_Title {
            get {
                return ResourceManager.GetString("NI1006_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Test classes must ultimately inherit from &apos;AutoTest&apos;..
        /// </summary>
        internal static string NI1007_Description {
            get {
                return ResourceManager.GetString("NI1007_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Test class &apos;{0}&apos; must ultimately derive from &apos;NationalInstruments.Core.TestUtilities.AutoTest&apos;.
        /// </summary>
        internal static string NI1007_Message {
            get {
                return ResourceManager.GetString("NI1007_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Test classes must ultimately inherit from &apos;AutoTest&apos;.
        /// </summary>
        internal static string NI1007_Title {
            get {
                return ResourceManager.GetString("NI1007_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Released APIs are monitored for backwards compatibility..
        /// </summary>
        internal static string NI1008_Description {
            get {
                return ResourceManager.GetString("NI1008_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string NI1008_Message {
            get {
                return ResourceManager.GetString("NI1008_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do not break backwards compatibility of released APIs.
        /// </summary>
        internal static string NI1008_Title {
            get {
                return ResourceManager.GetString("NI1008_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Internal members/types need to be have the VisibleInternalAttribute to be accessible..
        /// </summary>
        internal static string NI1009_Description {
            get {
                return ResourceManager.GetString("NI1009_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot access internal member/type &apos;{0}&apos; without VisibleInternalAttribute.
        /// </summary>
        internal static string NI1009_Message {
            get {
                return ResourceManager.GetString("NI1009_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Inaccessible internal member/type.
        /// </summary>
        internal static string NI1009_Title {
            get {
                return ResourceManager.GetString("NI1009_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Await call while holding a model lock or inside a transaction.  This can lead to hard-to-diagnose hangs and intermittent test failures.  If you have questions, contact the Platform Framework team..
        /// </summary>
        internal static string NI1015_Description {
            get {
                return ResourceManager.GetString("NI1015_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Await call while holding a model lock or inside a transaction.
        /// </summary>
        internal static string NI1015_Message {
            get {
                return ResourceManager.GetString("NI1015_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Await while holding a model lock or inside a transaction.
        /// </summary>
        internal static string NI1015_Title {
            get {
                return ResourceManager.GetString("NI1015_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do not lock directly on PrivateMemberLock.  This will not get the desired behavior of asserting if other locks are token. Instead, call Acquire()..
        /// </summary>
        internal static string NI1016_Description {
            get {
                return ResourceManager.GetString("NI1016_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do not lock directly on PrivateMemberLock - instead, call Acquire().
        /// </summary>
        internal static string NI1016_Message {
            get {
                return ResourceManager.GetString("NI1016_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do not lock directly on PrivateMemberLock.
        /// </summary>
        internal static string NI1016_Title {
            get {
                return ResourceManager.GetString("NI1016_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to If you invoke a chain of methods with lambda expressions in a single line, split each invocation (except the first one) onto its own line..
        /// </summary>
        internal static string NI1017_Description {
            get {
                return ResourceManager.GetString("NI1017_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Split chains of dotted method invocations with lambdas. Use well-named local variables if needed..
        /// </summary>
        internal static string NI1017_Message {
            get {
                return ResourceManager.GetString("NI1017_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Split chains of dotted method invocations with lambdas.
        /// </summary>
        internal static string NI1017_Title {
            get {
                return ResourceManager.GetString("NI1017_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do not use LINQ query syntax; use method syntax instead..
        /// </summary>
        internal static string NI1018_Message {
            get {
                return ResourceManager.GetString("NI1018_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do not use LINQ query syntax..
        /// </summary>
        internal static string NI1018_Title {
            get {
                return ResourceManager.GetString("NI1018_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Correct the spelling of &apos;{0}&apos; in assembly name {1}.
        /// </summary>
        internal static string NI1704_Assembly_Message {
            get {
                return ResourceManager.GetString("NI1704_Assembly_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Consider providing a more meaningful name than assembly name {0}.
        /// </summary>
        internal static string NI1704_AssemblyMoreMeaningful_Message {
            get {
                return ResourceManager.GetString("NI1704_AssemblyMoreMeaningful_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to In delegate {0}, correct the spelling of &apos;{1}&apos; in parameter name {2}.
        /// </summary>
        internal static string NI1704_DelegateParameter_Message {
            get {
                return ResourceManager.GetString("NI1704_DelegateParameter_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to In delegate {0}, consider providing a more meaningful name than parameter name {1}.
        /// </summary>
        internal static string NI1704_DelegateParameterMoreMeaningful_Message {
            get {
                return ResourceManager.GetString("NI1704_DelegateParameterMoreMeaningful_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The name of an externally visible identifier contains one or more words that are not recognized by the Microsoft spelling checker library..
        /// </summary>
        internal static string NI1704_Description {
            get {
                return ResourceManager.GetString("NI1704_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error parsing dictionary &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string NI1704_DictionaryParseError_Message {
            get {
                return ResourceManager.GetString("NI1704_DictionaryParseError_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Correct the spelling of &apos;{0}&apos; in member name {1}.
        /// </summary>
        internal static string NI1704_Member_Message {
            get {
                return ResourceManager.GetString("NI1704_Member_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Consider providing a more meaningful name than member name {0}.
        /// </summary>
        internal static string NI1704_MemberMoreMeaningful_Message {
            get {
                return ResourceManager.GetString("NI1704_MemberMoreMeaningful_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to In method {0}, correct the spelling of &apos;{1}&apos; in parameter name {2}.
        /// </summary>
        internal static string NI1704_MemberParameter_Message {
            get {
                return ResourceManager.GetString("NI1704_MemberParameter_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to In method {0}, consider providing a more meaningful name than parameter name {1}.
        /// </summary>
        internal static string NI1704_MemberParameterMoreMeaningful_Message {
            get {
                return ResourceManager.GetString("NI1704_MemberParameterMoreMeaningful_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to On method {0}, correct the spelling of &apos;{1}&apos; in generic type parameter name {2}.
        /// </summary>
        internal static string NI1704_MethodTypeParameter_Message {
            get {
                return ResourceManager.GetString("NI1704_MethodTypeParameter_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to On method {0}, consider providing a more meaningful name than generic type parameter name {1}.
        /// </summary>
        internal static string NI1704_MethodTypeParameterMoreMeaningful_Message {
            get {
                return ResourceManager.GetString("NI1704_MethodTypeParameterMoreMeaningful_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Correct the spelling of &apos;{0}&apos; in namespace name &apos;{1}&apos;.
        /// </summary>
        internal static string NI1704_Namespace_Message {
            get {
                return ResourceManager.GetString("NI1704_Namespace_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Consider providing a more meaningful name than namespace name &apos;{0}&apos;.
        /// </summary>
        internal static string NI1704_NamespaceMoreMeaningful_Message {
            get {
                return ResourceManager.GetString("NI1704_NamespaceMoreMeaningful_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Identifiers should be spelled correctly.
        /// </summary>
        internal static string NI1704_Title {
            get {
                return ResourceManager.GetString("NI1704_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Correct the spelling of &apos;{0}&apos; in type name {1}.
        /// </summary>
        internal static string NI1704_Type_Message {
            get {
                return ResourceManager.GetString("NI1704_Type_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Consider providing a more meaningful name than type name {0}.
        /// </summary>
        internal static string NI1704_TypeMoreMeaningful_Message {
            get {
                return ResourceManager.GetString("NI1704_TypeMoreMeaningful_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to On type {0}, correct the spelling of &apos;{1}&apos; in generic type parameter name {2}.
        /// </summary>
        internal static string NI1704_TypeTypeParameter_Message {
            get {
                return ResourceManager.GetString("NI1704_TypeTypeParameter_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to On type {0}, consider providing a more meaningful name than generic type parameter name {1}.
        /// </summary>
        internal static string NI1704_TypeTypeParameterMoreMeaningful_Message {
            get {
                return ResourceManager.GetString("NI1704_TypeTypeParameterMoreMeaningful_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Correct the spelling of &apos;{0}&apos; in variable name {1}.
        /// </summary>
        internal static string NI1704_Variable_Message {
            get {
                return ResourceManager.GetString("NI1704_Variable_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add this namespace to {0}.
        /// </summary>
        internal static string NI1800_CodeFixTitleFormat {
            get {
                return ResourceManager.GetString("NI1800_CodeFixTitleFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This is not an approved namespace. If this namespace is valid, please add it to the approved namespaces list..
        /// </summary>
        internal static string NI1800_Description {
            get {
                return ResourceManager.GetString("NI1800_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error reading approved namespaces file.
        /// </summary>
        internal static string NI1800_FileReadErrorMessage {
            get {
                return ResourceManager.GetString("NI1800_FileReadErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error reading file.
        /// </summary>
        internal static string NI1800_FileReadErrorTitle {
            get {
                return ResourceManager.GetString("NI1800_FileReadErrorTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} is not an approved namespace. If this namespace is valid, please add it to the approved namespaces list - {1}..
        /// </summary>
        internal static string NI1800_Message {
            get {
                return ResourceManager.GetString("NI1800_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No namespace approval files were found.
        /// </summary>
        internal static string NI1800_MissingApprovalFilesErrorMessage {
            get {
                return ResourceManager.GetString("NI1800_MissingApprovalFilesErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Missing namespace approval files.
        /// </summary>
        internal static string NI1800_MissingApprovalFilesErrorTitle {
            get {
                return ResourceManager.GetString("NI1800_MissingApprovalFilesErrorTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string NI1800_ParseError_Message {
            get {
                return ResourceManager.GetString("NI1800_ParseError_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This is not an approved test namespace. If this namespace is valid, please add it to the approved namespaces list..
        /// </summary>
        internal static string NI1800_TestDescription {
            get {
                return ResourceManager.GetString("NI1800_TestDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} is not an approved test namespace. If this namespace is valid, please add it to the approved namespaces list - {1}..
        /// </summary>
        internal static string NI1800_TestMessage {
            get {
                return ResourceManager.GetString("NI1800_TestMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not an approved test namespace.
        /// </summary>
        internal static string NI1800_TestTitle {
            get {
                return ResourceManager.GetString("NI1800_TestTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not an approved namespace.
        /// </summary>
        internal static string NI1800_Title {
            get {
                return ResourceManager.GetString("NI1800_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type derived from Disposable must not contain a finalizer..
        /// </summary>
        internal static string NI1816X_Description {
            get {
                return ResourceManager.GetString("NI1816X_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type name {0} must remove its finalizer.
        /// </summary>
        internal static string NI1816X_MessageFormat {
            get {
                return ResourceManager.GetString("NI1816X_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disposable should not have finalizer.
        /// </summary>
        internal static string NI1816X_Title {
            get {
                return ResourceManager.GetString("NI1816X_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string ParseError_Message {
            get {
                return ResourceManager.GetString("ParseError_Message", resourceCulture);
            }
        }
    }
}
