//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NationalInstruments.Tools.Analyzers.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NationalInstruments.Tools.Analyzers.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naming.
        /// </summary>
        internal static string CategoryNaming {
            get {
                return ResourceManager.GetString("CategoryNaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NationalInstruments.
        /// </summary>
        internal static string CategoryNI {
            get {
                return ResourceManager.GetString("CategoryNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of an externally visible identifier contains one or more words that are not recognized by the Microsoft spelling checker library..
        /// </summary>
        internal static string IdentifiersShouldBeSpelledCorrectlyDescription {
            get {
                return ResourceManager.GetString("IdentifiersShouldBeSpelledCorrectlyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing dictionary &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string IdentifiersShouldBeSpelledCorrectlyFileParse {
            get {
                return ResourceManager.GetString("IdentifiersShouldBeSpelledCorrectlyFileParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct the spelling of &apos;{0}&apos; in assembly name {1}..
        /// </summary>
        internal static string IdentifiersShouldBeSpelledCorrectlyMessageAssembly {
            get {
                return ResourceManager.GetString("IdentifiersShouldBeSpelledCorrectlyMessageAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider providing a more meaningful name than assembly name {0}..
        /// </summary>
        internal static string IdentifiersShouldBeSpelledCorrectlyMessageAssemblyMoreMeaningfulName {
            get {
                return ResourceManager.GetString("IdentifiersShouldBeSpelledCorrectlyMessageAssemblyMoreMeaningfulName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In delegate {0}, correct the spelling of &apos;{1}&apos; in parameter name {2}.
        /// </summary>
        internal static string IdentifiersShouldBeSpelledCorrectlyMessageDelegateParameter {
            get {
                return ResourceManager.GetString("IdentifiersShouldBeSpelledCorrectlyMessageDelegateParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In delegate {0}, consider providing a more meaningful name than parameter name {1}..
        /// </summary>
        internal static string IdentifiersShouldBeSpelledCorrectlyMessageDelegateParameterMoreMeaningfulName {
            get {
                return ResourceManager.GetString("IdentifiersShouldBeSpelledCorrectlyMessageDelegateParameterMoreMeaningfulName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct the spelling of &apos;{0}&apos; in member name {1}.
        /// </summary>
        internal static string IdentifiersShouldBeSpelledCorrectlyMessageMember {
            get {
                return ResourceManager.GetString("IdentifiersShouldBeSpelledCorrectlyMessageMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider providing a more meaningful name than member name {0}..
        /// </summary>
        internal static string IdentifiersShouldBeSpelledCorrectlyMessageMemberMoreMeaningfulName {
            get {
                return ResourceManager.GetString("IdentifiersShouldBeSpelledCorrectlyMessageMemberMoreMeaningfulName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In method {0}, correct the spelling of &apos;{1}&apos; in parameter name {2}.
        /// </summary>
        internal static string IdentifiersShouldBeSpelledCorrectlyMessageMemberParameter {
            get {
                return ResourceManager.GetString("IdentifiersShouldBeSpelledCorrectlyMessageMemberParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In method {0}, consider providing a more meaningful name than parameter name {1}..
        /// </summary>
        internal static string IdentifiersShouldBeSpelledCorrectlyMessageMemberParameterMoreMeaningfulName {
            get {
                return ResourceManager.GetString("IdentifiersShouldBeSpelledCorrectlyMessageMemberParameterMoreMeaningfulName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On method {0}, correct the spelling of &apos;{1}&apos; in generic type parameter name {2}..
        /// </summary>
        internal static string IdentifiersShouldBeSpelledCorrectlyMessageMethodTypeParameter {
            get {
                return ResourceManager.GetString("IdentifiersShouldBeSpelledCorrectlyMessageMethodTypeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On method {0}, consider providing a more meaningful name than generic type parameter name {1}..
        /// </summary>
        internal static string IdentifiersShouldBeSpelledCorrectlyMessageMethodTypeParameterMoreMeaningfulName {
            get {
                return ResourceManager.GetString("IdentifiersShouldBeSpelledCorrectlyMessageMethodTypeParameterMoreMeaningfulName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct the spelling of &apos;{0}&apos; in namespace name &apos;{1}&apos;..
        /// </summary>
        internal static string IdentifiersShouldBeSpelledCorrectlyMessageNamespace {
            get {
                return ResourceManager.GetString("IdentifiersShouldBeSpelledCorrectlyMessageNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider providing a more meaningful name than namespace name &apos;{0}&apos;..
        /// </summary>
        internal static string IdentifiersShouldBeSpelledCorrectlyMessageNamespaceMoreMeaningfulName {
            get {
                return ResourceManager.GetString("IdentifiersShouldBeSpelledCorrectlyMessageNamespaceMoreMeaningfulName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct the spelling of &apos;{0}&apos; in type name {1}..
        /// </summary>
        internal static string IdentifiersShouldBeSpelledCorrectlyMessageType {
            get {
                return ResourceManager.GetString("IdentifiersShouldBeSpelledCorrectlyMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider providing a more meaningful name than type name {0}..
        /// </summary>
        internal static string IdentifiersShouldBeSpelledCorrectlyMessageTypeMoreMeaningfulName {
            get {
                return ResourceManager.GetString("IdentifiersShouldBeSpelledCorrectlyMessageTypeMoreMeaningfulName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On type {0}, correct the spelling of &apos;{1}&apos; in generic type parameter name {2}..
        /// </summary>
        internal static string IdentifiersShouldBeSpelledCorrectlyMessageTypeTypeParameter {
            get {
                return ResourceManager.GetString("IdentifiersShouldBeSpelledCorrectlyMessageTypeTypeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On type {0}, consider providing a more meaningful name than generic type parameter name {1}..
        /// </summary>
        internal static string IdentifiersShouldBeSpelledCorrectlyMessageTypeTypeParameterMoreMeaningfulName {
            get {
                return ResourceManager.GetString("IdentifiersShouldBeSpelledCorrectlyMessageTypeTypeParameterMoreMeaningfulName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct the spelling of &apos;{0}&apos; in variable name {1}.
        /// </summary>
        internal static string IdentifiersShouldBeSpelledCorrectlyMessageVariable {
            get {
                return ResourceManager.GetString("IdentifiersShouldBeSpelledCorrectlyMessageVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiers should be spelled correctly.
        /// </summary>
        internal static string IdentifiersShouldBeSpelledCorrectlyTitle {
            get {
                return ResourceManager.GetString("IdentifiersShouldBeSpelledCorrectlyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All restricted types should be defined under &apos;NationalInstruments.Restricted&apos;..
        /// </summary>
        internal static string LRN001_Description {
            get {
                return ResourceManager.GetString("LRN001_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace &apos;{0}&apos; should be renamed to &apos;NationalInstruments.Restricted&apos;..
        /// </summary>
        internal static string LRN001_Message {
            get {
                return ResourceManager.GetString("LRN001_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is only one restricted namespace.
        /// </summary>
        internal static string LRN001_Title {
            get {
                return ResourceManager.GetString("LRN001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All types should be in the &apos;NationalInstruments&apos; namespace..
        /// </summary>
        internal static string LRT001_Description {
            get {
                return ResourceManager.GetString("LRT001_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not in the &apos;NationalInstruments&apos; namespace..
        /// </summary>
        internal static string LRT001_Message {
            get {
                return ResourceManager.GetString("LRT001_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All types are in &apos;NationalInstruments&apos; namespace.
        /// </summary>
        internal static string LRT001_Title {
            get {
                return ResourceManager.GetString("LRT001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To enable fully backwards-compatible database migrations in EntityFramework, all columns in the DB should be nullable. This means DbSet cannot use value types (unless they are marked as [NotMapped]) or types that implement IEnumerable&lt;T&gt; (we don&apos;t know how they&apos;ll be handled)..
        /// </summary>
        internal static string NI0017_Description {
            get {
                return ResourceManager.GetString("NI0017_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbSet uses an IEnumerable that we don&apos;t know how EntityFramework will handle: {0} for {1} in {2}.
        /// </summary>
        internal static string NI0017_Diagnostic_IEnumerable {
            get {
                return ResourceManager.GetString("NI0017_Diagnostic_IEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbSet creates non-nullable columns: {0} for {1} in {2} is a value type.
        /// </summary>
        internal static string NI0017_Diagnostic_ValueType {
            get {
                return ResourceManager.GetString("NI0017_Diagnostic_ValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database columns should be nullable.
        /// </summary>
        internal static string NI0017_Title {
            get {
                return ResourceManager.GetString("NI0017_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private field &apos;{0}&apos; must begin with an underscore and be camel-cased..
        /// </summary>
        internal static string NI1001_Message {
            get {
                return ResourceManager.GetString("NI1001_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private, mutable fields must begin with underscore and be camel-cased.
        /// </summary>
        internal static string NI1001_Title {
            get {
                return ResourceManager.GetString("NI1001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; with Scope &apos;{1}&apos; in file &apos;{2}&apos; is missing a Target value..
        /// </summary>
        internal static string NI1004_AttributeMissingTarget_Message {
            get {
                return ResourceManager.GetString("NI1004_AttributeMissingTarget_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rather than using string literals, use a string resource (.resx), unless this string will never be displayed to users..
        /// </summary>
        internal static string NI1004_Description {
            get {
                return ResourceManager.GetString("NI1004_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a string resource in a .resx file instead of string literal &apos;{0}&apos;..
        /// </summary>
        internal static string NI1004_Message {
            get {
                return ResourceManager.GetString("NI1004_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use string literals in code.
        /// </summary>
        internal static string NI1004_Title {
            get {
                return ResourceManager.GetString("NI1004_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IWeakEventListener.ReceiveWeakEvents() must return true..
        /// </summary>
        internal static string NI1005_Description {
            get {
                return ResourceManager.GetString("NI1005_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IWeakEventListener.ReceiveWeakEvents() must return true..
        /// </summary>
        internal static string NI1005_Message {
            get {
                return ResourceManager.GetString("NI1005_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not return false from IWeakEventListener.ReceiveWeakEvents().
        /// </summary>
        internal static string NI1005_Title {
            get {
                return ResourceManager.GetString("NI1005_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative: {0}.
        /// </summary>
        internal static string NI1006_AdditionalInfo_Alternative {
            get {
                return ResourceManager.GetString("NI1006_AdditionalInfo_Alternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned in this assembly..
        /// </summary>
        internal static string NI1006_AdditionalInfo_BannedInThisAssembly {
            get {
                return ResourceManager.GetString("NI1006_AdditionalInfo_BannedInThisAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justification: {0}.
        /// </summary>
        internal static string NI1006_AdditionalInfo_Justification {
            get {
                return ResourceManager.GetString("NI1006_AdditionalInfo_Justification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These methods have been banned from NG code. Contact an architect for explanation..
        /// </summary>
        internal static string NI1006_Description {
            get {
                return ResourceManager.GetString("NI1006_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace &apos;{0}&apos; with a non-banned method or get permission to suppress this rule.{1}  See http://nitalk.natinst.com/docs/DOC-153475 for more information.
        /// </summary>
        internal static string NI1006_Message {
            get {
                return ResourceManager.GetString("NI1006_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use banned methods.
        /// </summary>
        internal static string NI1006_Title {
            get {
                return ResourceManager.GetString("NI1006_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test classes must ultimately inherit from &apos;AutoTest&apos;..
        /// </summary>
        internal static string NI1007_Description {
            get {
                return ResourceManager.GetString("NI1007_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test class &apos;{0}&apos; must ultimately derive from &apos;NationalInstruments.Core.TestUtilities.AutoTest&apos;..
        /// </summary>
        internal static string NI1007_Message {
            get {
                return ResourceManager.GetString("NI1007_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test classes must ultimately inherit from &apos;AutoTest&apos;.
        /// </summary>
        internal static string NI1007_Title {
            get {
                return ResourceManager.GetString("NI1007_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released APIs are monitored for backwards compatibility..
        /// </summary>
        internal static string NI1008_Description {
            get {
                return ResourceManager.GetString("NI1008_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string NI1008_Message {
            get {
                return ResourceManager.GetString("NI1008_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not break backwards compatibility of released APIs.
        /// </summary>
        internal static string NI1008_Title {
            get {
                return ResourceManager.GetString("NI1008_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal members/types need to be have the VisibleInternalAttribute to be accessible..
        /// </summary>
        internal static string NI1009_Description {
            get {
                return ResourceManager.GetString("NI1009_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access internal member/type &apos;{0}&apos; without VisibleInternalAttribute.
        /// </summary>
        internal static string NI1009_Message {
            get {
                return ResourceManager.GetString("NI1009_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inaccessible internal member/type.
        /// </summary>
        internal static string NI1009_Title {
            get {
                return ResourceManager.GetString("NI1009_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Await call while holding a model lock or inside a transaction.  This can lead to hard-to-diagnose hangs and intermittent test failures.  If you have questions, contact the Platform Framework team..
        /// </summary>
        internal static string NI1015_Description {
            get {
                return ResourceManager.GetString("NI1015_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Await call while holding a model lock or inside a transaction..
        /// </summary>
        internal static string NI1015_Message {
            get {
                return ResourceManager.GetString("NI1015_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Await while holding a model lock or inside a transaction.
        /// </summary>
        internal static string NI1015_Title {
            get {
                return ResourceManager.GetString("NI1015_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not lock directly on PrivateMemberLock.  This will not get the desired behavior of asserting if other locks are token. Instead, call Acquire()..
        /// </summary>
        internal static string NI1016_Description {
            get {
                return ResourceManager.GetString("NI1016_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not lock directly on PrivateMemberLock - instead, call Acquire()..
        /// </summary>
        internal static string NI1016_Message {
            get {
                return ResourceManager.GetString("NI1016_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not lock directly on PrivateMemberLock..
        /// </summary>
        internal static string NI1016_Title {
            get {
                return ResourceManager.GetString("NI1016_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string ParseError_Message {
            get {
                return ResourceManager.GetString("ParseError_Message", resourceCulture);
            }
        }
    }
}
