//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NationalInstruments.Tools.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NationalInstruments.Tools.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown TagSelectionOption.
        /// </summary>
        public static string MetafileRepository_GetMetafiles_Unknown_TagSelectionOption {
            get {
                return ResourceManager.GetString("MetafileRepository_GetMetafiles_Unknown_TagSelectionOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing content-type boundary..
        /// </summary>
        public static string MultipartRequestHelper_GetBoundary_Missing_content_type_boundary_ {
            get {
                return ResourceManager.GetString("MultipartRequestHelper_GetBoundary_Missing_content_type_boundary_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to form-data.
        /// </summary>
        public static string MultipartRequestHelper_HasFormDataContentDisposition_form_data {
            get {
                return ResourceManager.GetString("MultipartRequestHelper_HasFormDataContentDisposition_form_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} should not be Null or Empty.
        /// </summary>
        public static string Verifier_VerifyArgumentIsNotNullOrEmpty_The_value__0__should_not_be_Null_or_Empty {
            get {
                return ResourceManager.GetString("Verifier_VerifyArgumentIsNotNullOrEmpty_The_value__0__should_not_be_Null_or_Empty" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected non-null variable {0} is null.
        /// </summary>
        public static string Verifier_VerifyValueIsNotNull_Expected_non_null_variable__0__is_null {
            get {
                return ResourceManager.GetString("Verifier_VerifyValueIsNotNull_Expected_non_null_variable__0__is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} should not be Empty.
        /// </summary>
        public static string Verifier_VerifyValueIsNotNullOrEmpty_The_value__0__should_not_be_Empty {
            get {
                return ResourceManager.GetString("Verifier_VerifyValueIsNotNullOrEmpty_The_value__0__should_not_be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} should not be Null.
        /// </summary>
        public static string Verifier_VerifyValueIsNotNullOrEmpty_The_value__0__should_not_be_Null {
            get {
                return ResourceManager.GetString("Verifier_VerifyValueIsNotNullOrEmpty_The_value__0__should_not_be_Null", resourceCulture);
            }
        }
    }
}
