# This is a basic workflow to help you get started with Actions

name: Main_CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1

      - name: Restore Nuget Packages
        run: dotnet restore NationalInstruments.Analyzers.sln

      - name: Build App
        run: dotnet build NationalInstruments.Analyzers.sln --configuration release --no-restore

      - name: Run Tests
        run: dotnet test NationalInstruments.Analyzers.sln

